### ISSUE TITLE
Why not just js-ipld-eth?

### ISSUE THREAD

**Issue by jbenet** [ipld/js-ipld-eth-account-snapshot#5]
hey @kumavis and @diasdavid 

- Why not just one module `js-ipld-eth`? 
- Is it _useful_ to distinguish them? Maybe there's something i'm not seeing?
- Having to make 6 different ipld format modules (assign a code, parsers, etc) because ethereum's data is not self-describing does not necessarily mean that it is good for developers to think of these as 6 different things.
- i claim that a new developer would find more utility from a `js-ipld-eth` package that has all six inside, than 6 individual packages plus a seventh tying them all together.

```
js-ipld-eth/account-snapshot
js-ipld-eth/transaction

// vs

js-ipld-eth-account-snapshot
js-ipld-eth-transaction
```

**Comment by jbenet** [comment]
(btw, i personally dont care very much :) you two know best!)

**Comment by diasdavid** [comment]
If the question is: 'multiple repos vs single repo', I'm fine either way :)

It might make it easier for @kumavis, since they share the same codebase, avoiding to create 'yet another repo' to export that shared base.

@kumavis your call! :)

**Comment by kumavis** [comment]
sure, would likely be easier to maintain. but im not available to work on making this change atm.

**Comment by diasdavid** [comment]
This is happening! https://github.com/ipld/js-ipld-ethereum/issues/4
